export const questions = [
    {
      id: 1,
      question: "What is the capital of France?",
      options: ["Berlin", "Madrid", "Paris", "Rome"],
      answer: "Paris",
      initialScore: 2,
    },
    {
      id: 2,
      question: "Who wrote 'To Kill a Mockingbird'?",
      options: ["Harper Lee", "Mark Twain", "Ernest Hemingway", "Toni Morrison"],
      answer: "Harper Lee",
      initialScore: 2,
    },
    {
      id: 3,
      question: "What is 2 + 2?",
      options: ["3", "4", "5", "6"],
      answer: "4",
      initialScore: 2,
    },
    {
      id: 4,
      question: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Venus", "Jupiter"],
      answer: "Mars",
      initialScore: 2,
    },
    {
      id: 5,
      question: "What gas do plants absorb from the atmosphere?",
      options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
      answer: "Carbon Dioxide",
      initialScore: 2,
    },
    {
      id: 6,
      question: "What is the largest mammal on Earth?",
      options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
      answer: "Blue Whale",
      initialScore: 2,
    },
    {
      id: 7,
      question: "In which continent is the Sahara Desert located?",
      options: ["Asia", "Africa", "Australia", "South America"],
      answer: "Africa",
      initialScore: 2,
    },
    {
      id: 8,
      question: "Which language has the most native speakers?",
      options: ["English", "Spanish", "Hindi", "Mandarin"],
      answer: "Mandarin",
      initialScore: 2,
    },
    {
      id: 9,
      question: "Which country hosted the 2016 Summer Olympics?",
      options: ["China", "Brazil", "UK", "Russia"],
      answer: "Brazil",
      initialScore: 2,
    },
    {
      id: 10,
      question: "What is H2O commonly known as?",
      options: ["Oxygen", "Water", "Hydrogen", "Salt"],
      answer: "Water",
      initialScore: 2,
    },
    {
      id: 11,
      question: "Who painted the Mona Lisa?",
      options: ["Van Gogh", "Leonardo da Vinci", "Michelangelo", "Picasso"],
      answer: "Leonardo da Vinci",
      initialScore: 2,
    },
    {
      id: 12,
      question: "What is the boiling point of water at sea level?",
      options: ["90°C", "100°C", "120°C", "80°C"],
      answer: "100°C",
      initialScore: 2,
    },
    {
      id: 13,
      question: "What is the hardest natural substance on Earth?",
      options: ["Iron", "Diamond", "Gold", "Quartz"],
      answer: "Diamond",
      initialScore: 2,
    },
    {
      id: 14,
      question: "What is the longest river in the world?",
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      answer: "Nile",
      initialScore: 2,
    },
    {
      id: 15,
      question: "Who developed the theory of relativity?",
      options: ["Isaac Newton", "Albert Einstein", "Galileo", "Stephen Hawking"],
      answer: "Albert Einstein",
      initialScore: 2,
    },
    {
      id: 16,
      question: "Which organ pumps blood through the body?",
      options: ["Lungs", "Brain", "Heart", "Liver"],
      answer: "Heart",
      initialScore: 2,
    },
    {
      id: 17,
      question: "What currency is used in Japan?",
      options: ["Yen", "Won", "Dollar", "Peso"],
      answer: "Yen",
      initialScore: 2,
    },
    {
      id: 18,
      question: "Which instrument has 88 keys?",
      options: ["Guitar", "Violin", "Piano", "Flute"],
      answer: "Piano",
      initialScore: 2,
    },
    {
      id: 19,
      question: "Which element has the symbol 'O'?",
      options: ["Gold", "Oxygen", "Osmium", "Olive"],
      answer: "Oxygen",
      initialScore: 2,
    },
    {
      id: 20,
      question: "What is the tallest mountain in the world?",
      options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Denali"],
      answer: "Mount Everest",
      initialScore: 2,
    },
  ];
  